name: shopping_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.12.0
  get_it: ^5.0.3
  injectable: ^1.0.7
  bloc: ^7.0.0
  responsive_framework: ^0.1.0
  flutter_bloc: ^7.0.0
  persistent_bottom_nav_bar: ^4.0.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.12.7
  injectable_generator: ^1.0.7
  lint: ^1.0.0
  auto_route_generator: ^0.6.10
  build_runner:


flutter:

  uses-material-design: true

